name: Trigger auto deployment for container-app-3b2c7bbpv6qys

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-3b2c7bbpv6qys-AutoDeployTrigger-f422704c-f4d5-4027-a905-861f6a146bd9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3B2C7BBPV6QYS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3B2C7BBPV6QYS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3B2C7BBPV6QYS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3B2C7BBPV6QYS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3B2C7BBPV6QYS_REGISTRY_PASSWORD }}
          containerAppName: container-app-3b2c7bbpv6qys
          resourceGroup: miabetodo0707bfbd
          imageToBuild: default/container-app-3b2c7bbpv6qys:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


